### ISSUE TITLE
References/testing steps using IE/WAT are wildly outdated

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wai-easy-checks#115]
The latest version of IE is getting sunsetted by Microsoft this summer, and WAT has not seen an update in probably a decade or more. As IE/WAT is featured heavily in https://www.w3.org/WAI/test-evaluate/preliminary/, the whole document probably needs a good rewrite to replace it with more modern tools.

**Comment by shawna-slh** [comment]
It very much needs a significant revision. Known issue. In case you're interested: we [started](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2019_Project_Plan)  a project plan to implement **["Next Gen" ideas](https://www.w3.org/WAI/EO/wiki/Easy_Checks_Next_Gen)**. Then didn't have enough people able to commit time to it.

I am very much hoping that we can get to it in 2022 under the [WAI-CooP project](https://www.w3.org/WAI/about/projects/wai-coop/)!

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource

**Comment by patrickhlauke** [comment]
Is this new version out already, or is this a future update?

**Comment by patrickhlauke** [comment]
Ah, got it, thanks Kevin
