### ISSUE TITLE
bookmarklets, browser toolbars, other tools, etc.

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#127]
We are considering ways for the resource to **provide specific guidance**, yet **not be so cluttered** and **not get so out of date**. Some options for providing instructions:

1. browser "Web Developer" toolbar (one of the tools in the current version) that works on several browsers
2. [bookmarklets](https://www.w3.org/WAI/EO/wiki/Easy_Checks_2019_Project_Plan#Bookmarklets_for_Accessibility_Evaluation)/favlets
3. free tools such as WAVE

Notes:
* The current resource says: "You can do most of these checks with any browser, that is, you do not need to download special tools. However, some checks are easier if you can download tools."
* If we offered instructions for more than one option, we could provide filtering. The current version includes instructions for: multiple browsers and toolbars, keyboard and mouse, Windows and Mac. Users could filter for which of those they want to show or hide. That would add complexity for us developing the next generation of the resource, yet more options and simplicity for users.

Questions:
a. What are pros and cons of each option?
b. What limitations will some users have for each option, e.g., in a tightly locked down environment?

_See also_ **[10 March 20023 EOWG minutes](https://www.w3.org/2023/03/10-eo-minutes#item04)**

**Comment by shawna-slh** [comment]
Howard _(comment moved from wiki page)_:
> Most people use 3rd party tools. ... I don't think newbies want to install a bunch of individual favlets or scripts.

**Comment by MicheleAWilliams-A11y** [comment]
Seems like an opportunity to send people to the Evaluation Tools list where hopefully there would be tools there that can help. Ideally this would even be a direct URL with the appropriate filters applied so it lists their options automatically. Since W3C doesn't have actual tools, seems problematic to maintain this page based on third party tools.

**Comment by iadawn** [comment]
Just to expand a little bit on the thinking and limitations behind the approach.

The constraits that feed into any solution on approach are:

*  Needs to be future proofed as much as possible - this reduces the need to monitor changes in the technologies and approaches suggested. It also reduces the risk of the resource going out of date too quickly.
* Needs to support non-technical people - this includes people who may look at
  ```<img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/5d64d52c-015e-4b04-a4d5-7eca27080f8c/d6jydgj-efd70a99-181d-4832-bbb5-3a3df0176b8d.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvNWQ2NGQ1MmMtMDE1ZS00YjA0LWE0ZDUtN2VjYTI3MDgwZjhjXC9kNmp5ZGdqLWVmZDcwYTk5LTE4MWQtNDgzMi1iYmI1LTNhM2RmMDE3NmI4ZC5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.9FfyI7cRwhyqSzHC5ujqAe2WUVDzRQnS5l-K5g4jf98" alt="Space cat">```
  and glaze over a bit, even with instructions.
* Needs to support people who cannot install plug ins or other tools - from personal experience, this is the whole of the public sector in Scotland! And there are likely to be many other areas where installing third party tools is problematic.

While this would limit the options for tools that we can present, we could still provide general tool-agnostic information regarding:

* What is the issue
* Why is it important and to whom
* What do good an bad look like

All of this information is relevant regardless of what tool is used - as long as it can conduct the actual check. The bit where we would need to consider the constraints outlined above a bit more is:

* How to check

We will look to take a pass at creating a mockup of how this all might look to better explain things, but the above just highlights some of the thinking behind the proposed solution.

**Comment by hkramer** [comment]
Again, I would vote for using something like WAVE. It's widely used, easy to install (and can be used off the WebAIM site if user is not allowed to install extension). There's also a lot of info in the WAVE tool for more information.
I could see providing instructions for more than one tool though it increases the work on the resource. Directing folks to the tool list is also a good idea. As I said in the meeting, I think Favlets is too cumbersome to install.

**Comment by iadawn** [comment]
Thanks @hkramer, I agree wth your points regarding use and additional information. I do feel that WAVE output can be overwhelming as there is no way to filter the findings. I know that this can be an issue for some less technical user groups and some sites where there are a huge number of issues. 

Unfortunately there are instances where WAVE, even the website, is not usable.

In Scottish Government we would often be testing sites or services that were in development or internally deployed. This were not available external to the networks they were running on. The only tools that worked in this instance were browser developer tools (which required the user to know HTML to understand problems) or bookmarklets that did not use third party libraries such as jQuery.

I wonder if it is worth exploring both options with in the section on 'How to check' and outlining when each would work?

**Comment by shawna-slh** [comment]
I do wonder if the ideal for users would be a resource that provides guidance for checking with: 1. nothing beyond a browser, 2. bookmarklets, 3. Web Developer toolbar, 4.+ generic for common tools, such as WAVE, or specific for free tools (to avoid vendor neutrality issues, we would have to open it up for any tool to submit, or provide it as CC for others to use, or something)

And enable users to choose to get the instructions for whichever they wanted. Such [filtering was the previous "Next Gen" idea](https://www.w3.org/WAI/EO/wiki/Easy_Checks_Next_Gen#Specific_instructions.2C_filtering).

However, that greatly increases the work needed -- both now to develop it and later to maintain it. (We could set it up so it's easier for community to help maintain, now that more are familiar with GitHub. Though that still requires some resources from us.)

I think we can find a happy medium that works well for users and is less work for us.

**Comment by AndrewArch** [comment]
I'm a little late to the discussion, but thanks all for the recent discussion on pros & cons of different tool options, I'm thinking a multi-pronged (step wise) approach is probably the way to go given what everyone has said :)
