### ISSUE TITLE
[not essential] first page - fix text in yellow box

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#132]
> If you are looking for help on a more thorough review of accessibility or detailed information, check the Evaluation Tools list or the WCAG instead.

This text is wrong. See the list under "[Encourage thorough accessibility evaluation](https://www.w3.org/WAI/test-evaluate/preliminary/#next)" after "Guidance is available from". If we don't want that whole list, then can point to [Evaluating Web Accessibility Overview](https://www.w3.org/WAI/test-evaluate/).

**Comment by iadawn** [comment]
Note that this text is not intended to be definitive.

In this case though, please use the following text:

> These checks are not definitive. A web page could seem to pass these checks, yet still have significant accessibility barriers.
>
> These checks help identify just a few accessibility issues. There are other accessibility issues not covered in these easy checks, for example: links, data table, reliance on color, and much more.
>
> Find out more about [Evaluating Web Accessibility](https://www.w3.org/WAI/test-evaluate/)
