### ISSUE TITLE
[medium] first page - delete technical info

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#134]
Please delete:

> In technical terms, 'alt' is an attribute of an image in HTML.

and

> In the HTML headings are marked as ```<hn>``` where 'n' indicates the level of the heading.

These totally go against the purpose of the resource to speak to non-techies.

... now I see they are at the top of the checks, too. I think that needs to be reformulated -- though I guess you won't be able to do that before our testing.

**Comment by jasperjeurens** [comment]
Agreed, we're violating some of our earlier defined content requirements with this first content integration iteration.
