### ISSUE TITLE
alt text page has headings info

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#139]
https://xd.adobe.com/view/7d05cad8-234d-437d-82d9-4290a5018440-2856/screen/6bb9ef64-43b8-4ee7-89c8-cdccfaf3ce86?fullscreen&hints=off

"Other ways to check" section is about headings, not alt text.

(@brianelton I got this :-)

**Comment by iadawn** [comment]
@jasperjeurens could you fix this one too?

**Comment by jasperjeurens** [comment]
fixed (good catch!)
