### ISSUE TITLE
high - modal boxes - close button styling should be consistent - some are missing 

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-easy-checks#162]
Location: 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/image-alt/ - close button missing
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/title/ - "X"
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/heading-structure/ - "Close"
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/ - close button missing
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/ - close button missing
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/keyboard-focus/ - close button missing
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/language/ - "X"
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/form-field-labels/ - close button missing
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/required-fields/ - close button missing

**Comment by iadawn** [comment]
Hi Laura, thanks for this... this may highlight a flaw in my thinking. There are two types of bookmarklet being used:

* One which provides a quick bit of information and then you close it - for example, Title or Language. For these ones the 'find out more' link is included in the dialog.
* One which changes the page to flag bits of content, which isn't closed - for example, Images or Required fields. For these the 'find out more' link is put in a fixed window in the bottom right hand of the view port.

Now that you flag it, the inconsistency may not be idea.

I could:

* Leave it as is; or
* Add a close link to the second group as well which would remove all the elements that have been changed on the page?

I suspect the latter would be best but would welcome your thoughts.

**Comment by AndrewArch** [comment]
@iadawn Noticing that (some of) the modals don't allow for 'esc' to close them. They don't trap the keyboard either, but I presume that was a decision to allow the user could still explore the page without resetting?
