### ISSUE TITLE
(med) Easy check for H1 of Heading Structure

### ISSUE THREAD

**Issue by JediLin** [w3c/wai-easy-checks#164]
Location: 
page: Heading Structure - Easy Checks. Subsection: [What to look for](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/heading-structure/#what-to-look-for)

Current wording:
Did the the list start with an H1?

Suggested revision:
Did the highest rank (smallest number) of the list be an H1?

Rationale:
[Example 2](https://www.w3.org/WAI/tutorials/page-structure/headings/#main-heading-after-navigation) from Headings tutorial in the W3C Page Structure tutorial results a heading list NOT started with an H1.

Related issues:
It seems that there is no suggestion on following topic related to heading structure:
- What's the difference (or indifference) between a page Title and its H1?
- Should H1 be consistent (always be the name of the site, for example) across pages, or should it be the section heading of the `<main>`?

**Comment by iadawn** [comment]
I think the suggested text is a bit more complicated than necessary but there is a change needed. Proposing to change it to:

* Is the first heading in the list of headings marked as level 1?

This might benefit from an image as well.

Regarding related issues; I think these are getting into details that are beyond the intended audiences.

**Comment by iadawn** [comment]
Sure, but I think it is worth remembering that the primary audiences are not indented to be conducting audits where false failures would be an issue.

**Comment by JediLin** [comment]
For our target audience, a procurer, for example, might use these checks to get the idea if a vendor can deliver accessible products. I don't like to have false failures in such situations.

To keep things simple and easy, I propose this revision:
- Did the list have an H1?

**Comment by AndrewArch** [comment]
I think we might be becoming too simple now - just having an H1 doesn't say anything about good heading structure as the site could use an H1 anywhere if they wanted a particular heading style.

I'll think about this and try and come up with a good solution.

**Comment by iadawn** [comment]
ef396ca Changes some of the things to check for in headings.

@JediLin, @AndrewArch Do these now work for you and address this issue?

**Comment by JediLin** [comment]
> [ef396ca](https://github.com/w3c/wai-easy-checks/commit/ef396ca6e5b5c043619ee5c0cf6d1a811cbf7b80) Changes some of the things to check for in headings.

Isn't this updating icon-keyboard-focus image?

Anyway, I like `Ideally the page starts with an "h1"` from https://github.com/w3c/wai-easy-checks/issues/214#issue-2038956789

**Comment by iadawn** [comment]
Doh... misused my GitHub client: 9eb37bf

**Comment by JediLin** [comment]
I don't think the false failure issue is addressed.
In my previous [proposal](https://github.com/w3c/wai-easy-checks/issues/164#issuecomment-1848941824), I don't think that will cause "just having H1" situation @AndrewArch [worried](https://github.com/w3c/wai-easy-checks/issues/164#issuecomment-1849639686), for there is `Do the headings accurately represent the structure of the content, particularly nested content?`

**Comment by iadawn** [comment]
Can you say more on the false failure?

Also, bear in mind that this isn't aimed at being an audit check so I would be less keen on putting in nuanced checks.

**Comment by JediLin** [comment]
I don't worry about false pass since easy checks are not audit checks.
On the other hand, I think it's vital that we reduce false failure as possible.

For the target audience of these easy checks, they might use these checks as baseline filters and reject all failure cases. There usually won't be follow-up audit for these rejected cases.

Note: If the main purpose of easy checks is for education, it's totally fine to have false failure.

**Comment by iadawn** [comment]
Closing as it doesn't undermine the main purpose of the checks
