### ISSUE TITLE
(high) Summaries on main page

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-easy-checks#172]
Suggest more consistency in the summaries on the main page. 

Suggest what the topic is, why it's important. 

E.g. Alt text
Original
Image alternative text (“alt text”) is a short description that conveys the purpose of an image. Alternative text is used by people who do not see the image. For example, people who are blind and use screen readers can hear the alt text read out.

New
Image alternative text (“alt text”) is a short description that conveys the purpose of an image. Alternative text is used by people who do not see the image. 

I'll keep adding to these here.

**Comment by jade-mc** [comment]
Keyboard focus. 

Change to 
Keyboard focus is a visible indicator that identifies the element with focus and moves as your tab through a page. For people who rely on a keyboard to navigate it is important that they know which link or form control has focus.

**Comment by jade-mc** [comment]
Language of page (there's a typo in that title btw). 

Web pages should identify the primary language of the page. Specifying the language of the page means that assistive technology that speaks content can correctly pronounce words.

**Comment by jade-mc** [comment]
Captions

Just the order changed here. 

@iadawn major typo in this one btw... 

Captions are a text version of the speech and non-speech audio information needed to understand the video. The audio in video content needs to be available to people who are dea**f** or hard of hearing.

**Comment by jade-mc** [comment]
Audio description

Audio description describes visual information needed to understand the content, including text displayed in the video. It provides content to people who are blind and others who cannot see the video adequately.

**Comment by jade-mc** [comment]
Done :)

**Comment by AndrewArch** [comment]
thanks for the suggestions re consistency @jade-mc  :)

**Comment by iadawn** [comment]
Merged in Andrew's PR to address this
