### ISSUE TITLE
(High) Non-mouse instructions for bookmarklets

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#174]
**Location:** 
Throughout, for each bookmarklet; for example "Image Alternative Text"

**Current wording:**
Drag the _XYZ_ link to your browser bookmarks

Suggested revision:
@frankie-wolf is going to help

Rationale:
We'll need text for how to do this without a mouse.

**Comment by frankie-wolf** [comment]
[like]  Frankie Wolf reacted to your message:
________________________________

**Comment by KosiAsabere** [comment]
e wording could be , offering more detailed guidance. Browser Specific Installation Help:

Chrome:

To show the Bookmarks Bar in Chrome, press Ctrl + Shift + B.
To install an accessibility tool on Chrome using the keyboard:
Press Ctrl + Shift + O to bring up the Bookmark Manager.
Select the menu button (three vertical dots) in the top right of the Bookmark Manager to open a context menu.
Select "Add New Bookmark".
Name the bookmark identically to the linked test tool.
Copy and paste the JavaScript URL of the specific accessibility tool.
Press Save.
Edge (Chromium):

To show the Favorites Bar in Edge, press Ctrl + Shift + B.
To install an accessibility tool on Edge using the keyboard:
In the Edge address bar, navigate to: edge://favorites/
Select "Add Favorite" button.
Name the bookmark identically to the linked test tool.
Copy and paste the JavaScript URL of the specific accessibility tool.
Press Save.
Firefox:

To show the Bookmarks Bar in Firefox, Press (Alt + V), select Toolbars, then "Bookmarks Toolbar".
To install an accessibility tool on Firefox using the keyboard:
Right-click this link Ctrl + Shift + F10: [Test Tool Name]
Select "Bookmark This Link".
Internet Explorer:

To show the Favorites Bar in Internet Explorer, Press Alt + V, select Toolbars, then "Favorites Bar".
To install an accessibility tool on Internet Explorer using the keyboard:
Right-click this link Ctrl + Shift + F10: [Test Tool Name]
Select "Add to favorites bar".
Safari:

To show the Favorites Bar in Safari, Press Command + Shift + B.
Unfortunately, Safari does not offer a simple keyboard accessible alternative to set a JavaScript favelet link as a favorite.
Launching the Accessibility Tool:

Launch the tool by clicking on the favorite/bookmark labeled with the name of the linked test tool that was added to the Favorites/Bookmarks Bar in the browser's toolbar. The tool will then perform its specific function.

**Comment by KosiAsabere** [comment]
I understand that our aim is to avoid creating browser-specific instructions. However, if we decide to include a separate page specifically for keyboard instructions, this is a sample of how the wording could be structured

**Comment by iadawn** [comment]
Hmm... that looks like a headache for the future.

What about:

* Ctrl/Cmd + D 
* Open context menu on link and copy link address
* Navigate to added bookmark and edit it
* Paste into the link address

I think all of those are keyboard accessible approaches and don't rely on browser specific instructions

@AndrewArch Anything from your colleague?
@frankie-wolf Were you able to find any text?

**Comment by KosiAsabere** [comment]
@iadawn  your suggestion is the better solution if it works on all the different browsers. Let me do a test with this just to confirm that  in Firefox,, chrome  and edge that it achieves the desired result.

**Comment by KosiAsabere** [comment]
@iadawn, I noticed that the instructions don't mention the need for the browser's bookmarks bar to be visible. This is a key point, as the visibility of the bookmarks bar might vary across the browsers.

**Comment by KosiAsabere** [comment]
@iadawn  how about this?:




# Displaying the Bookmarks Bar
1. **Open Your Browser:**
   - Launch the web browser you normally use.

2. **Access Browser Settings/Menu:**
   - Find and open the browser menu. This is typically indicated by an icon with three dots or lines, located at the top corner of the browser window.

3. **Locate Bookmarks Settings:**
   - In the menu, look for an option related to bookmarks or favorites. It might be labeled 'Bookmarks', 'Favorites', or something similar.

4. **Enable Bookmark Bar:**
   - Within the bookmarks settings, find and select an option like 'Show Bookmark Bar' or 'Enable Bookmark Bar'.
   - This option might be a checkbox or a simple command.

5. **Confirm Visibility:**
   - The bookmark bar should now be visible, usually below the address bar.

# Adding a Bookmarklet to the Bookmark Bar
## Using a Mouse:
- **Navigate to the Bookmarklet:**
  - Go to the page where the bookmarklet is located.
- **Drag the Bookmarklet:**
  - Click and hold the bookmarklet link.
  - Drag it to your bookmark bar.
- **Release to Add:**
  - Drop the bookmarklet on the bookmark bar by releasing the mouse button.

## Using Keyboard Only:
- **Navigate to the Bookmarklet:**
  - Use the 'Tab' key to navigate to the bookmarklet link on the page.
- **Open Context Menu:**
  - With the bookmarklet link focused, press the 'Applications' key or 'Shift' + 'F10' to open the context menu.
- **Copy the Link:**
  - Use the arrow keys to find 'Copy link address' or similar and press 'Enter' to copy it.
- **Access the Bookmark Bar:**
  - Navigate to the bookmark bar using 'Tab' or access the bookmarks menu with the browser's keyboard shortcut.
- **Create a New Bookmark:**
  - In the bookmarks menu, select 'Add Bookmark' or 'New Bookmark'.
- **Paste the Link:**
  - In the URL field, paste the bookmarklet link (use 'Ctrl' + 'V' on Windows/Linux or 'Cmd' + 'V' on Mac).
- **Save the Bookmarklet:**
  - Name your bookmarklet and save it to the bookmark bar.

**Comment by iadawn** [comment]
Hmm... Andrew and I have been working on this and we have not been able to work out how to open the context menu using a keyboard on the Mac. This makes it a little difficult to use a keyboard only to do this so I may have to rethink the instructions or approach.

I have tried an experiment in [Skip Link](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/)

**Comment by iadawn** [comment]
Additionally I am still hesitant about writing material to tell folks how to use their browser. I wonder whether pointing to other resources such as https://www.computerhope.com/issues/ch001917.htm might be more productive.

**Comment by AndrewArch** [comment]
Hmmm - the computerhope link goes to mouse type instructions. What if we add a sentence to the instruction 4 in the [Skip Link](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/) experiment like [You can find the keystrokes for your browser by searching for "(browser name) keyboard shortcuts"] just to give them a nudge?

**Comment by iadawn** [comment]
[Skip links](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/) includes an alternative approach to this. This is necessary because on the Mac it is not possible to open a context menu using they keyboard only.

This approach:

* Includes an expand/collapse heading with the text "Add bookmark using keyboard only"
* Includes a simple button that will copy the bookmarklet script to the clipboard
* Provides step by step instructions on how to set up the bookmark
* Reduces maintenance challenges by avoiding browser/OS specifics but does hint what people can search for if they are not aware of appropriate shortcuts

@MicheleAWilliams-A11y, @frankie-wolf, @KosiAsabere, @daniel-montalvo - could you all have a go with this to see if it works for you. If so, I can use it as an approach for the other checks.

**Comment by shawna-slh** [comment]
> @iadawn how about [this](https://github.com/w3c/wai-easy-checks/issues/174#issuecomment-1856384402)?:

+1 for this type of info (on a separate page on how to use the bookmarklet, since bookmarklet are essential for this iteration of resource).

This wording approach provide fairly specific instructions that do not need to be updated frequently.

I do think we can get rid of the nesting, and maybe simplify a bit.

**Comment by iadawn** [comment]
The type of info is fine but I have a number of problems with this:

* I have deliberately avoided the word 'bookmarklet' - it was clear that most people don't know what these are and it was discussed at TPAC and agreed to avoid it as much as possible
* The instructions necessarily refer back to the check page. If people are using these then it would require flipping back and forward between the two pages for it to make sense. This assumes that the suggestion is to have these instructions on the separate page only ... if the idea is to have instructions on both the check page and an instructions page then this is pointless as it would be better to get them right where they are presented.
* While I appreciate this is a proposal there are problems with it which have meant taking an in-page approach. Specifically you can't open a context menu using the keyboard on a Mac. This makes a big difference to how to set up the check for use.
* It is not clear that there are extensive problems with the mouse instructions. The lack of 'make sure your bookmarks bar is open' is the main issue here. Feedback on the keyboard only instructions is so far extremely limited and that is something I would like to pursue before solving an unclear problem.

**Comment by MicheleAWilliams-A11y** [comment]
Hi there, regarding whether the instructions for keyboard work, I wasn't able to directly edit the bookmark URL without specifically going into the "Bookmark Manager" in Chrome to replace the URL. That is, the "Edit" path using Command-D didn't allow this (I'm using Chrome on MacOS). 

Nonetheless, the "copy to clipboard" feature was really helpful and overall this concept might also help mouse users who can't do the drag motion but also wouldn't necessarily use keyboard commands. 

With that, perhaps we simplify the instructions to something like the following to cover all cases (and replicate this strategy for other pages):

> **Check Other Pages**
> You'll need to place this tool in your browser bookmarks/favorites. 
> 
> To start, expand your Bookmarks/Favorites bar. You can select "Show Bookmarks Bar" in your browser menu or press Control+Shift+B on Windows or Command+Shift+B on Mac.
> 
> Once expanded, use one of the following to add this tool to your bookmarks:
> 
> - Drag this link to the bar: Check skip link
> - Copy this link then right click on the bar and paste it: Copy to clipboard
> - Navigate to your Bookmarks Manager (Control+Shift+O on Windows, Option+Command+B on Mac) then create a bookmark with this copied link: Copy to clipboard

**Comment by shawna-slh** [comment]
Let's keep this issue about the non-mouse instructions. And have the discussion about how to handle bookmark tools ("bookmarklets") in the [discussion](https://github.com/w3c/wai-easy-checks/discussions/243).

@@ TO DO  - Shawn reply to some comment above there.

**Comment by iadawn** [comment]
For the moment, I have added the same keyboard instructions to all checks that use bookmarklets.

I am hesitant to blend the drag-and-drop and keyboard instructions together as I suspect that will become messy, quickly. However, it might be worth revisiting this in the near future.

**Comment by frankie-wolf** [comment]
Non-mouse instructions for MacOS on Chrome:
1. Activate the Copy script to clipboard button. Press Enter or Spacebar to copy the script.
2. Press Enter or Spacebar to dismiss the confirmation that the script was copied.
3. Open the Bookmarks Manager by pressing Option + Command + B.
4. In Bookmarks Manager, activate the Organize button and then select Add new bookmark.
5. In the Name field, enter a name for this (what’s the word if we’re not using bookmarklet?), such as “Skip Link Checker.”
6. In the URL field, paste the script you copied in Step 1.
7. Activate the Save button.

**Comment by KosiAsabere** [comment]
@frankie-wolf +1 to your  instructions. They look great and  are clear and concise.  

As far as the name goes, How about "bookmark tool"?

**Comment by frankie-wolf** [comment]
@KosiAsabere thanks! I saw "Bookmark Bar Tool" in the [Improving Bookmarklet Usability in WAI Easy Checks](https://github.com/w3c/wai-easy-checks/discussions/243) discussion, so that's what I've used here. No strong feelings on the right one, since I've always used bookmarklet/favelet to describe these things.

This is a first attempt at a a more general version of this process on Mac. Note I did encounter some differences between browsers in Step 1:

1. Navigate to and activate the Copy script to clipboard button. {Press Enter or Spacebar to copy the script.) **Notes:** When using Safari, press TAB until you get to the “Add link using keyboard only” heading, then press Option + TAB to set focus on the button; otherwise, it’s skipped. When using Edge, neither the Enter or Spacebar copy the script.
2. Press Enter or Spacebar to dismiss the confirmation that the script was copied.
3. Add a bookmark/favorite:
    * **Chrome:** Open the Bookmarks Manager by pressing **Option + Command + B**. Activate the **Organize** button and then select **Add new bookmark**.
    * **Edge:** Open the Favorites by pressing Option + Command + B. Activate the Add this page to Favorites button.
    * **Safari:** Open Bookmarks by pressing Option + Command + B. Press Control + D, then activate the Add button. 
4. When adding the bookmark/favorite, use a memorable name to remind you of what the bookmark bar tool does, like “Skip Link Checker.”
5. Update the URL by pasting the script you copied in Step 1.

You can use the built-in features of your browser to organize these bookmark bar tools into a folder for easy checks. To run the bookmark bar tool:
1. Open the page you want to check.
2. Navigate to the Bookmarks/Favorites in your browser and then activate the bookmark you created. The script will run and provide you with feedback about the accessibility issue you’re checking.

**Comment by iadawn** [comment]
Closing as we have implemented an approach for keyboard users. If there are specific issues, please open separately so we can address.
