### ISSUE TITLE
(low) Short description text wrapping below icon

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#176]
Location: [Easy Checks landing page](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/)

Current formatting: When the short description of each easy check wraps to three lines or more, the text flows under the icon image

Suggested formatting: When the short description text wraps to a new line, each new line stays aligned with the one above it.

Rationale: Easy of reading

**Comment by iadawn** [comment]
I have addressed this, although please check with a narrow viewport.

**Comment by brianelton** [comment]
did a quick check and it looks good!
