### ISSUE TITLE
(med) Page title best practice tips

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#179]
Location: [Page Title - Tips](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/title/#tips)

**Current wording:**

Better page titles:
- Acme Web Solutions home page
- About Acme Web Solutions
- Contact Acme Web Solutions
- History of Acme Web Solutions

**Suggested revision:**

Better page titles:
- Acme Web  Solutions
- About us - Acme Web Solutions
- Contact us - Acme Web Solutions
- Our History - Acme Web Solutions

**Rationale:**
One best practice that I always suggest is that the page title should match the h1 of the page, which rarely includes the name of the company. Separating the page name from the site name allows this to happen much more easily, particularly with content management systems.

**Comment by iadawn** [comment]
Not sure I am sold on this. The [related tip](https://www.w3.org/WAI/tips/writing/#provide-informative-unique-page-titles) has:

> The page title is often the same as the main heading of the page

And the example used comes from the existing [Easy Checks page](https://www.w3.org/WAI/test-evaluate/preliminary/#title).

And there isn't anything that would require them to match. The 'better' example provided is certainly better than the poor example; front loaded and clear what is on the page. I wonder if it might be help to include either/or?

* Acme Web Solutions *or* Acme Web Solutions home page
* About us - Acme Web Solutions *or* About Acme Web Solutions

etc

**Comment by brianelton** [comment]
I had originally written this to just add an entire OR section that had my updates and keeping the original "Better page titles" list. I'm fine with your alternative version.
