### ISSUE TITLE
(med) "Impairment" vs "Disability"

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#180]
Location: [Heading Stucture - Who depends on Headings?](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/heading-structure/#who-depends-on-headings)

Current wording: "Headings help people with cognitive and learning or reading impairments"

Suggested revision: "Headings help people with cognitive and learning or reading disabilities"

Rationale: Consistency in the use of the word disability. I realize this is regional and there may be many other instances of "impairment" but generally wanted to flag this as something that may need to be adjusted overall.

**Comment by iadawn** [comment]
Changed

Note @shawna-slh, this might be something we want to address in the style guide - unless it is already there and I have just neglected to read it... again
