### ISSUE TITLE
(low) Clarify what is needed for contrast checking tools

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#182]
Location: [Color Contrast - Accurate check](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/#accurate-check)

Current wording: Other tools need you to know what the code is for the colors being checked.

Suggested revision: Other tools need you to know what the RGB or HEX code is for the colors being checked.

Rationale: Clarity

**Comment by iadawn** [comment]
We will then need to explain RGB and HEX code?

**Comment by brianelton** [comment]
perhaps. But even if we don't, someone having to ask "what is an RGB code?" could be better than asking "what is the 'code'?"

**Comment by iadawn** [comment]
What about something like:

* Other tools need you to know what the color code is for the colors being checked. For example, , #eed009 is the code for a gold/yellow color. 

We could possibly link to [Simple Wikipedia](https://simple.wikipedia.org/wiki/RGB) in this case, @shawna-slh?

**Comment by brianelton** [comment]
I like this. I would change what is linked though, as that is going to a page about RGB, not hex, as is the example.

**Comment by AndrewArch** [comment]
So, could say

- Other tools need you to know what the [color code](https://simple.wikipedia.org/wiki/RGB) is for the colors being checked. For example, RGB (238, 208, 9) or Hex #eed009 is the code for a gold/yellow color.
