### ISSUE TITLE
(low) Heading Structure: Only One Heading on the page

### ISSUE THREAD

**Issue by yjlucyh** [w3c/wai-easy-checks#184]
Location: 
Heading Structure > [What is Heading Structure?](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/heading-structure/)*

Suggestion: Does it need to point out only one Heading 1 on each page? This is the best practice. I can see there's one H1 in the image and on the [Headings in Page Structure Tutorial](https://www.w3.org/WAI/tutorials/page-structure/headings/) page.

When I tested websites, many pages had more than one H1. It is not a failure but not best practice.

**Comment by iadawn** [comment]
I am not sure that this topic has a straight forward answer. I have seen opinion and commentary on both sides of this. Given that it is not a failure or requirement then I would not be inclined to include it.
