### ISSUE TITLE
(low) Captions: Add Language Learners to the Captions Users

### ISSUE THREAD

**Issue by yjlucyh** [w3c/wai-easy-checks#185]
Location: Captions - Easy Checks > [Who depends on Captions?](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/captions/#main)

Suggestion: Should we add language learners? For example, English as a second language learners, but this is not just for English because the resource will be used worldwide.

Rationale: Honestly, as an English as a second language user, sufficient captions help me a lot. Cations give us a chance to learn new words and we may check the meaning to help us understand the content. Also, this is especially important in educational institutions for international students, in my opinion.

**Comment by iadawn** [comment]
The current position is to focus on issues that are important for accessibility rather than broader benefits. Many of the broader benefits are discussed in other resources and the plan is to link to them.

If you feel this is not the right approach, please contribute to the linked discussion: #241
