### ISSUE TITLE
(low) General Comment for the "What to look for" Section

### ISSUE THREAD

**Issue by yjlucyh** [w3c/wai-easy-checks#187]
Location: "What to look for" section on some pages, for example: 
[Image Alternative Text - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/image-alt/)
[Form Field Labels - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/form-field-labels/)

Current wording: 
(1) Image Alternative Text page, the third list item is: Images that are decorative should be noted as having an empty alt text attribute (**‘Alt text=””. Suitable?’**)
(2) Form Field Labels page, the second list item is: After using the ‘Check field labels’ link, check that there are no fields marked with **‘✗ Missing label’**

Suggested revision: If we have screenshots with proper alt text instead of ‘Alt text=””. Suitable?’ or "‘✗ Missing label,’ is it easier to understand? For example:
Images that are decorative should be noted as having an empty alt text attribute (![image](https://github.com/w3c/wai-easy-checks/assets/151180941/1e731cfa-9414-404d-aa0d-806f08c96500))
 vs 
Images that are decorative should be noted as having an empty alt text attribute (‘Alt text=””. Suitable?’)"

 
Rationale: When I reviewed the alt text page, there are many punctuations, it is hard to understand in the beginning. And the examples above don't have empty/null alt text so it is not easy to catch.

**Comment by iadawn** [comment]
Added in images to demonstrate what to look for
