### ISSUE TITLE
(low) Language - Easy Checks; demo page link 

### ISSUE THREAD

**Issue by lbeaze** [w3c/wai-easy-checks#190]
Location: 
[Language - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/language/) 

Current wording:
Paul Adam bookmarklet - Note, this is the actual bookmarklet. There is no demo page for this one. Uses jQuery

Suggested revision:
Paul Adam bookmarklet. Uses jQuery

with this demo page link ...
https://pauljadam.com/bookmarklets/focus.html

Rationale:
Follows the pattern of using demo pages established on other Easy Checks.

**Comment by iadawn** [comment]
Acknowledgement content is there as a reminder to do this. It is not presented as it will be in final draft.
