### ISSUE TITLE
(med) Confusing 'What to look for' in skip link page

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#192]
Location: [Skip link - What to look for](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/#what-to-look-for)

Current wording: "Sometimes the skip link is not the first link on a page. The checking tool provided here only checks the first link that skips down the current page. This may not be an actual skip link. This means there is a problem with the skip link."

Suggested revision: "Sometimes the skip link is not the first link on a page. The checking tool provided here only checks the first link that skips down the current page. It is possible that this link is an in-page link and not one that skips to main content. This means that either there is no skip link or that there is a problem with it."

Rationale: Trying to be clearer on what the tool may find if not a skip link.

**Comment by iadawn** [comment]
I have adapted the wording slightly
