### ISSUE TITLE
(med) Language - acknowledgements section structured differently than keyboard focus

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#198]
**Location:** [Language - Acknowledgements](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/language/#acknowledgements)

**Current wording:**

The bookmarklet is based on the work by Paul Adam.

bookmarklets:

**Suggested revision:**

The bookmarklet is based on the work by Paul Adam.

**Rationale**: To match the acknowledgements in the keyboard focus page and remove redundancy.

**Comment by iadawn** [comment]
This is only a temporary record of the acknowledgments. They will be update either with a completely separate page or added in the footer
