### ISSUE TITLE
(high) Transcripts - typo

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#204]
Location: [Transcripts - Who depends on transcripts](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/transcripts/#check-transcript-quality)

Current wording: "Is all the speach accurately reflected in the transcript?"

Suggested revision: "Is all the speech accurately reflected in the transcript?"

Rationale: Irony

**Also**

Current wording: "Are all other sounds described in the transcript, such as ‘soft clapping’ or ‘tyres screeching’?"

Suggested revision: "Are all other sounds described in the transcript, such as ‘soft clapping’ or ‘tires screeching’?"

Rationale: US spelling

**Comment by iadawn** [comment]
What is Noah's problem with 'tyre'!?!? He didn't respell 'lyre'!!!

Mutter mutter mutter
