### ISSUE TITLE
(high) Audio Description - missing svg

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-easy-checks#205]
Location: [Audio Description - Checking audio description](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/description/#checking-audio-description)

Issue: Missing svg image in second bullet point

**Comment by iadawn** [comment]
Oh it is there... I just can't get it to pay attention to the CSS colour!!!

**Comment by brianelton** [comment]
I still don't see it... I know the code is there but nothing is showing!

**Comment by iadawn** [comment]
Fixed now... forgot to make the URI relative!
