### ISSUE TITLE
The “What to look for” Heading contents should come before the practice button example.

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#206]
## Template for comments:

level: medium,  
page: [page title](URL) All sub pages
location Under Checking this page
"
current wording: “This is just for practice. Also, you can see what the check will look like on an accessible page.
suggested revision: The “What to look for” Heading contents should come before the same page example.
rationale: Rationale:
It is important that users know what to look for before they activate the button. Putting the "What to look for" heading before the button will help avoid any potential confusion and help users better anticipate any changes that might occur on the page. Making this change will likely improve the flow of the content and make the instructions more clear.

**Comment by iadawn** [comment]
The practice button is not intended to provide an example that they are thoroughly checking. It is really there to just show what will happen. Putting it before the button will confuse things as people will be told what to check for before the how to check.
