### ISSUE TITLE
(high) Who depends on -> Why it's important

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#208]
Page: all sub-pages

Location: second section heading

Current wording: Who depends on [topic]?

Suggested revision: Why it's important
_or maybe:_ Why [topic] is important

Rationale:
* The [usability testing in May](https://docs.google.com/document/d/1pm87OM0Mk32MJTokbjh_w02NcbLclVSZ/edit) clearly identified that "Who depends on" did not work. Users said they were looking for "why" and most did not associate "Who depend on" with "Why".
* "Why it's important" is stronger and clearer and simpler than "Who depends on"
* Similar to wording in the tutorials (e.g., [Page Structure](https://www.w3.org/WAI/tutorials/page-structure/))
* "Why it's important" wording was refined with EOWG and some in AG WG, and is now used in the What's New in WCAG pages and the Understanding docs.

**Comment by AndrewArch** [comment]
Interesting that the "why" in the Page Structure tutorial is essentially a list of "who" :)

**Comment by iadawn** [comment]
Fixed in 059c1e2
