### ISSUE TITLE
(med) link or button ? (low) visual browser toolbar-ish?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#210]
Page: most sub-pages

Location: Checking this page

Current wording:
> click on the link below:
> [visual design looks like a button]

Suggested revision: _either_
> click the button below:
> [visual design looks like a button]

_or_
> click on the link below:
> [visual design looks like a link]

Rationale: match wording to visual -- *and* match with screen reader identification as well

Other: I wonder about making it a clickable image that looks like it would in a browser bookmark bar? (of course genericized so not browser specific)

**Comment by iadawn** [comment]
I can change the wording to be 'click on the button'. However, I can't change the element to be a `<button>` without some considerable work. If at all.

This means that the text doesn't match the role as a screen reader user would perceive it.

I could add a `role="button"` attribute which might be a quick fix.

Open to thoughts

**Comment by AndrewArch** [comment]
Kevin I had the same thought last week re 'button' vs 'link', but then saw you'd addressed it visually and and with code. Fine for now and probably for the future.
