### ISSUE TITLE
(med) Heading Structure -> Headings

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#214]
Page: [Heading Structure](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/heading-structure/)
Location: heading, title, and throughout

Current wording: "Heading Structure" and lots of the text

Suggested revision: "Headings" and lots of the text

Rationale: Keep it simple and focused on the most important points, and avoid quality details.

I think this page currently focuses on way too much on structure and levels.

Instead, I think it should focus more on if headings are generally marked up well (ideally without having to say "mark up" :) From [headings in previous version](https://www.w3.org/WAI/test-evaluate/preliminary/#headings):
> * The page has a heading. In almost all pages there should be at least one heading.
> * All text that looks like a heading is marked up as a heading.
> * All text that is marked up as a heading is really a conceptual section heading.
> * The heading hierarchy is meaningful. Ideally the page starts with an "h1" — which is usually similar to the page title — and does not skip levels; however, these are not absolute requirements.

**Comment by shawna-slh** [comment]
I looked around and it seems only the page heading was changed. This is also about the content of the page. Sorry not just a quick fix.

> Location: ... throughout
> Current wording: "Heading Structure" **and lots of the text**
> Suggested revision: "Headings" **and lots of the text**
> ...

**Comment by iadawn** [comment]
> Suggested revision: "Headings" and lots of the text

I need something more specific than that. I reviewed the content and change a couple of things that related to 'heading structure'. If there is something else, please specify and I can address it.

**Comment by lbeaze** [comment]
@iadawn  the sidenav-list has this page listed as 'Heading Structure'. Everything else says 'Headings'.
