### ISSUE TITLE
(Med) [December] Add "To Do" placeholder text for bookmarklet keyboard-only instructions

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#219]
Location: 
Throughout

Current Wording:
For now we have the "drag" language for bookmarklets. 

Suggested Revision:
Just add a simple "To Do: Input keyboard instructions" message.

Rationale:
Since the team is working on writing keyboard alternatives for bookmarklets, I think it's helpful to expose that work just to prevent people from commenting on it or think we won't have them.

**Comment by AndrewArch** [comment]
Added as TODO until we finalise the keyboard instructions
