### ISSUE TITLE
(Med) Typo in link on Alt Text page

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#220]
Location: 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/image-alt/

Current wording:
[User story of someone relyng on image alternative text to understand the page information](https://www.w3.org/WAI/people-use-web/user-stories/#accountant)

Suggested revision:
Need to update "relyng" to "relying"

**Comment by iadawn** [comment]
Fixed with 69ccf63
