### ISSUE TITLE
(Med) Reverse examples of "Who depends on good page titles?"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#221]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/title/

Heading > Who depends on good page titles?

**Current wording:**
Screen reader users need good page titles. The first thing screen readers say when the user goes to a different web page is the page title.
Good page titles are particularly important for orientation — to help people know where they are and move between pages open in their browser.

**Suggested revision:**
_Reverse the sentences..._

**Rationale:**
So they read from broad to specific and also so that we don't reinforce that accessibility is solely about screen reader compatibility.

**Comment by iadawn** [comment]
Reordered
