### ISSUE TITLE
(Low) Clean up tips for page titles

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#222]
Location: 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/title/

Current wording:
There is flexibility on what makes a good page title. However best practice is for the important and unique information to come first. This is called “front-loading”.

Suggested revision:
There is flexibility on what makes a good page title. However, best practice is for the important and unique information to come first; this is called “front-loading”.

Rationale:
Adding punctuation to help this read more smoothly.

**Comment by iadawn** [comment]
Added in comma. Not sure on the semi-colon. In my mind it makes the sentence a little bit more complex for not that much value. Happy for you to reopen and convince me otherwise :)
