### ISSUE TITLE
(High) Make headings example an HTML list

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#223]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/headings/

**Current wording:**
Headings communicate the organization of the content on the page. They are like a table of contents. They are nested by their rank or level. They help provide a summary of the structure and content of a page. For example:

```
  <h1> Headings - Easy Checks
    <h2> What are Headings?
    <h2> Who depends on Headings?
    <h2> Checking Headings
      <h3> Checking this page
      <h3> Checking other pages
      <h3> What to look for
    <h2> Learn more
    <h2> Acknowledgements
    <h2> Help improve this page
```

**Suggested revision:**
In the code, make this an unordered list (`<ul>`) without visual bullet icons.

**Rationale:**
So that this indentation is conveyed to AT users. Willing to overlook this if there's a reason not to, but seems like it would be needed since currently it distills to essentially one paragraph of text.

**Comment by iadawn** [comment]
In the code this is marked up using `<code>`. I think this is the correct use since the section of text is a code example. Using `<ul>` would communicate the nesting to AT but I think it would be semantically incorrect.
