### ISSUE TITLE
(Med) Determine if check will be Capital or lowercase

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#224]
(Updated this issue once I saw there was a pattern...)

**Location:** 
Throughout.

**Current wording:**
Throughout the checks, sometimes the keyboard is capitalized in the headings, starting with "Headings". Prior to that (such as in "page titles" ) it is not.

**Suggested revision:**
Be consistent. I prefer lowercase for grammatical accuracy, but if this is meant to stand out that's fine as well.

**Rationale:**
The guides need consistency.

**Comment by iadawn** [comment]
Fixed with 96f0569
