### ISSUE TITLE
(Med) Contrast Contrast typo with "it's"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#225]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

**Current wording:**
Technically, color contrast is the relative luminance of two or more colors to each other, particularly between text and **it’s** background. 

**Suggested revision:**
Technically, color contrast is the relative luminance of two or more colors to each other, particularly between text and **its** background. 

**Rationale:**
Grammatical fix

**Comment by AndrewArch** [comment]
oops :( corrected :)
