### ISSUE TITLE
(Med) Color Contrast - Complete the last sentence of "who depends on"

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#226]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

**Current wording:**
Many people use colored filters or overlays on their screens or devices **so need good color contrast**

**Suggested revision:**
Many people use colored filters or overlays on their screens or devices so **they** need good color contrast

Rationale:
This needed revising to flow correctly; update suggested seems the most straightforward

**Comment by iadawn** [comment]
Fix with [e6fd210](https://github.com/w3c/wai-easy-checks/commit/e6fd2108dc3387bec5757bd0ed212d5141b7f59c)
