### ISSUE TITLE
(Med) Reorder content in the Color Contrast Checks section for easier scanning

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#227]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

**Current wording:**
Quick check
Click on the button below:

[Check grayscale on this page]

This gives a rough check as to whether the text on the page is easily read or needs increased contrast.

**Suggested revision:**
Quick check
Determine contrast levels based on viewing the page in grayscale. 

Use button below to check this page:
[Check grayscale on this page]

**Rationale:**
I clicked the button without really reading the text, and it seemed like nothing happened at first because the page doesn't have a lot of color to start with. I had to search around to understand what happened and what to expect.

**Comment by AndrewArch** [comment]
Thanks Michele - taken onboard
