### ISSUE TITLE
(Med) The Color Contrast checker tool has 404 link

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#228]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

The bookmarklet has a link in its pop-up that says "Checking Color Contrast" but the link doesn't go anywhere (see photo):
![Screenshot 2023-12-15 at 1 59 10 PM](https://github.com/w3c/wai-easy-checks/assets/84785057/379cf4cb-136b-4859-b165-d543357d674f)

Is this supposed to happen? Seems confusing if so.

**Comment by iadawn** [comment]
These are all set with the URLs that will work when the resource is finally published. It is a bit of a challenge to make them work before that happens! Each of the links will link to the current page - when it is published and the check is used on another page it will link people through to the background page.
