### ISSUE TITLE
(Med) Proposed updated language for Color Contrast section

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#229]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

**Current wording:**
Accurate Check
You can use tools to test more thoroughly. These will do the math and then tell you whether there is sufficient contrast.

There are many tools out there to help check the contrast between your text and the background. Some tools allow you to sample the colors directly. Other tools need you to know what the [color code](https://simple.wikipedia.org/wiki/RGB) is for the colors being checked. For example, RGB (238, 208, 9) or Hex #eed009 is the code for a gold/yellow color.

To find tools that will help, search the [Evaluation Tools List](https://www.w3.org/WAI/ER/tools/) for ‘color’ or ‘colour’.

**Suggested revision:**
To test more thoroughly, use tools that will do the math and tell you if the colors meet the correct ratios for sufficient contrast. Search the [Evaluation Tools List](https://www.w3.org/WAI/ER/tools/) for ‘color’ or ‘colour’ to find such tools.

Notably, some tools will allow you to sample the colors directly (such as use an eye dropper to select the colors) while others require knowing the [color code](https://simple.wikipedia.org/wiki/RGB). Example color codes are "RGB (238, 208, 9)" or "Hex #eed009" and are generally known by design team members.

**Rationale:**
The current wording doesn't quite flow and the link for the Evaluation Tools List gets buried in the text.

**Comment by iadawn** [comment]
I have made some changes based on the suggested revision. I have moved the link to the Evaluation Tools List into another paragraph and front loaded the link as much as is sensible to make it more prominent.
