### ISSUE TITLE
(Med) Explain how to turn off the Color Contrast bookmarklet

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-easy-checks#230]
**Location:** 
https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/

**Situation**
When I activated the Color Contrast Grayscale button, I didn't know how to turn it off. Turns out you need to close the dialog but I only did this by accident, and before that I was somewhat panicked.

**Suggestion:**
Add text under the button that says "To return to full color, close the dialog that appears". 

Note: This relates to ticket #227

**Comment by AndrewArch** [comment]
Good suggestion - added
