### ISSUE TITLE
(med) Content issue title: switch sentences in paragraph under "visible keyboard focus checks,"  on landing page

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#235]
Review

**Level:** Medium
**Page:** [Easy Checks – A First Review of Web Accessibility](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/#common)
**Location:** Under "Visible Keyboard Focus" heading

**Current Wording:**
"For people who rely on a keyboard to navigate it is important that they know which link or form control has focus. Keyboard focus is a visible indicator that identifies the element with focus and moves as your tab through a page."

**Suggested Revision:**
"Keyboard focus is a visible indicator that identifies the element with focus and moves as your tab through a page. For people who rely on a keyboard to navigate, it is important that they know which link or form control has focus."

**Rationale:**
Switch the sentence order so that it matches the structure of the previous easy check content on the main page. The other easy check topics before describe what the easy check is before they mention why it’s important.

**Comment by KosiAsabere** [comment]
Correction:  Change "Your" to "you".

**Comment by AndrewArch** [comment]
Thanks for picking up the inconsistency @KosiAsabere
