### ISSUE TITLE
(Med) Clarification needed in Labeling Instructions for Form Fields**

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#237]
**Level:** Med

**Page:** [Form Field Labels - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/form-field-labels/)

**Location:** Under the "What to look for" heading, first paragraph

**Current Wording:**
"There are many ways to provide a label for screen reader users. To support mouse users, form elements must have a programmatically associated label. When using the ‘Check field labels’ link, this is shown by the form element being marked as ‘Labelled’ and the form label being marked with ‘Label for field with ID=…’. For example,”

**Suggested Revision:**
"There are many ways to provide a label. To support assistive technology users, including mouse users, form elements must have a programmatically associated label. When using the ‘Check field labels’ link, this is shown by the form element being marked as ‘Labelled’ and the form label being marked with ‘Label for field with ID=…’. For example, ??"

**Rationale:**
 it is uncertain whether the first sentence is connected to the others. The paragraph needs to be clearer, especially for the intended audience. It is not clear how the first sentence, which refers to screen readers, relates to the subsequent sentences. For example, is a “programmatically associated label” only beneficial to mouse users?

**Comment by iadawn** [comment]
Fixed with [9a7c6e5](https://github.com/w3c/wai-easy-checks/commit/9a7c6e53521ba6acacc4f1fca1d98759c41318e1)
