### ISSUE TITLE
(Med) Content Issue: Need to provide more context before the “Check images on this page” 

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#238]
**Level:** Medium  
**Page:** [Image Alternative Text - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/image-alt/)  
**Location:** Under "Checking this page" heading

### Current Wording:
> Checking Image Alternative Text  
> Checking this page  
> This is just for practice. Also, you can see what the check will look like on an accessible page.
>
> Click on the button below:  
> Check images on this page

### Suggested Revision:
> Checking Image Alternative Text  
> Checking this page
>
> "Press the button to show each image's alt text on the page.  
> If an image doesn't have alt text, it will be highlighted, showing where you can make improvements."
>
> Click on the button below:

### Rationale:
"We need to provide more context before the bookmarklet, so users don't have to scroll back and forth to understand what's happening. This is especially important for people who need to zoom or are using mobile devices. Providing a short description of what the bookmarklet does will also be helpful to screen

**Comment by iadawn** [comment]
Repeat of #240, will address as part of that.
