### ISSUE TITLE
(Med) Content Suggestion: Check page title on this page” bookmarklet needs clearer instructions ( before button) for better usability 

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#239]
**Level:** Medium  
**Page:** [Page Title - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/image-alt/)  
**Location:** Under "Checking this page" heading

### Current Wording:
> Checking page titles  
> Checking this page  
> This is just for practice. Also, you can see what the check will look like on an accessible page.
>
> Click on the button below:  
> Check page title on this page

### Suggested Revision:
> Checking Image Alternative Text  
> Checking this page
>
> "Press the button to check the page's title. A pop-up will appear which will help you find out if the title is missing or not set up correctly. You can close this pop-up to continue viewing the page."
>
> Click on the button below:

### Rationale:
"We need to provide more context before the bookmarklet, so users don't have to scroll back and forth to understand what's happening. This is especially important for people who need to zoom or are using mobile devices. Providing a short description of what the bookmarklet does will also be helpful to screen reader users and others, even if they cannot use the bookmarklet or are having trouble getting the tool to work. Context needs to be added before all easy check bookmarklets to improve usability.

**Comment by iadawn** [comment]
Repeat of https://github.com/w3c/wai-easy-checks/issues/240, will address as part of that.
