### ISSUE TITLE
(Low) Typo: Change “covert” to “convert”on contrast page

### ISSUE THREAD

**Issue by KosiAsabere** [w3c/wai-easy-checks#244]
Level:** Low  
**Page:** [Color Contrast - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/color-contrast/)  
**Location:** Under "Checking other pages"

### Current Wording:
1. "Drag this link to your browser bookmarks bar: [Covert to grayscale](#)
2. Visit the page you want to check
3. Click on the ‘Covert to grayscale’ link in your bookmarks
4. To return to full color, close the dialog that appears"

### Suggested Revision:
1. "Drag this link to your browser bookmarks bar: [Convert to grayscale](#)
2. Visit the page you want to check
3. Click on the ‘Convert to grayscale’ link in your bookmarks
4. To return to full color, close the dialog that appears"

### Rationale:
There's a typo in the instructions. The word “Covert” should be corrected to “Convert” to accurately reflect the action described.

**Comment by iadawn** [comment]
Fixed
