### ISSUE TITLE
(high) Add more specific alt text for skip link image [January]

### ISSUE THREAD

**Issue by frankie-wolf** [w3c/wai-easy-checks#250]
Location:
Skip Link - Easy Checks, “What is a skip link?”, first paragraph, image [Skip Link - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/skip-link/)

Current wording: alt="Example of a skip link"

Suggested revision: alt=“An example of a skip link: a highlighted area with the text ’Skip to Content’ directs users to the main heading on the page.”

Rationale: Reduce cognitive load for people brand new to accessibility and to be more inclusive for users with visual disabilities. Also consider making this type of change in a visible text alternative.

**Comment by iadawn** [comment]
I feel that the proposed revision adds more content than is necessary to the alt text. What skip links do is explained in the text following so repeating this would just add more noise for some AT users.
