### ISSUE TITLE
(med) Add more specific alt text for headings image [January]

### ISSUE THREAD

**Issue by frankie-wolf** [w3c/wai-easy-checks#251]
Location: 
page: Headings - Easy Checks. under "Who depends on headings?" heading, image after first paragraph" [Headings - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/headings/)*

Current wording: alt="Example of screen reader generated list of headings"

Suggested revision: alt="Example of a screen reader generated list of headings that includes the heading level and the heading text."

Rationale: Reduce cognitive load for people brand new to accessibility and to be more inclusive for users with visual disabilities. Also consider making this type of change in a visible text alternative.

**Comment by iadawn** [comment]
The proposed text is already included in the previous paragraph. I feel that repeating this would just add unnecessary text for some AT users.
