### ISSUE TITLE
(high) Alt text is swapped on the German and Japanese examples [January]

### ISSUE THREAD

**Issue by frankie-wolf** [w3c/wai-easy-checks#252]
Location: 
page: Language - Easy Checks. under "How is Language identified?" heading, two images [Language - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/language/)*

Current wording: alt text for Japanese page says German and alt text for German page says Japanese

Suggested revision: Swap the alt text

Rationale: This is a bug.

**Comment by iadawn** [comment]
Fixed
