### ISSUE TITLE
(high) Missing alt attribute on image [January]

### ISSUE THREAD

**Issue by frankie-wolf** [w3c/wai-easy-checks#253]
Location: 
page: Captions - Easy Checks. under "What are captions?" heading, image. [Captions - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/captions/)

Current wording: N/A

Suggested revision: Add alt text

Rationale: The image is not accessible for users without vision.

**Comment by iadawn** [comment]
It is arguable whether this image is decorative or not. However, in the interests of consistency with the other screenshots, I have included alt text.
