### ISSUE TITLE
(medium) Add more specific alt text for required fields images [January]

### ISSUE THREAD

**Issue by frankie-wolf** [w3c/wai-easy-checks#257]
Location: page: Required Fields - Easy Checks. under "What is a Required Field?" heading, images. [Required Fields - Easy Checks](https://deploy-preview-131--wai-easychecks.netlify.app/test-evaluate/easy-checks/required-fields/)

Current wording image 1: alt="Example of field with asterisk to mark required status"

Suggested revision image 1: alt="A form that indicates all required fields are marked with an asterisk, with the first field labeled First Name with an asterisk"

Current wording image 2: alt="Example of field with text to mark required status"

Suggested revision image 2: alt="A form that indicates all required fields are marked, with the first field labeled First Name (required)"

Rationale: Reduce cognitive load for people brand new to accessibility and to be more inclusive for users with visual disabilities. Also consider making this type of change in a visible text alternative that includes the actual text included in the image to solidify the example.

**Comment by iadawn** [comment]
I feel that the proposed changes do not add any pertinent information. The purpose of the image is to show a form field with either an asterisk or text to highlight the required nature of the field. The following text goes on to explain more specifics of this. Repeating the content in the alt text just adds more noise for some AT users.
