### ISSUE TITLE
[bug] link in bookmarklet results gives 404

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#260]
**Describe the bug**
link in bookmarklet results gives 404 'cause URI is missing ```/test-evaluate```

**To Reproduce**
1. Go to https://www.w3.org/WAI/test-evaluate/easy-checks/title/
2. Click Check title on this page
3. Click [Checking Page Title](https://www.w3.org/wai/easy-checks/title/)
4. 404

**Expected behavior**
goes to https://www.w3.org/WAI/test-evaluate/easy-checks/title/

**Comment by iadawn** [comment]
Fixed in [02c562b](https://github.com/w3c/wai-easy-checks/commit/02c562b90f983160e8a7918f639e9f3e81ff7543)
