### ISSUE TITLE
(med) Typo - Headings page

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-easy-checks#266]
URL: https://www.w3.org/WAI/test-evaluate/easy-checks/headings/

Location: 
Under "Who depends on headings", third paragraph

Current wording: 
Headings also help people with cognitive and learning or reading disability.

Suggested revision: 
Headings also help people with cognitive and learning or reading **_disabilities_**.

Rationale: 
To me it should be plural as three disabilities are mentioned.

**Comment by iadawn** [comment]
Done... not quite sure when, but done
