### ISSUE TITLE
Captions  [@@ say more ?]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#28]
Noticed this @@:

> Automatic captions are not sufficient for accessibility because they are not accurate enough. For example, in YouTube, if only "automatic captions" are listed (as in the image above), there are no sufficient captions and the video is not accessible. Captions in the specific language need to be listed. [@@ say more ?]

**Comment by yatil** [comment]
I think we should remove the @@ part from the document for this release and then explore what else we want to say. We should not have it holding us up without a concrete proposal.

**Comment by slhenry** [comment]
+1

Commented out @@ and labeled etc this for later

Also, there are a couple other @@s in comments that we could look at sometime...

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
