### ISSUE TITLE
[Feature Request] Consider accessibility bookmarklets for simple testing of headings and landmarks

### ISSUE THREAD

**Issue by jongund** [w3c/wai-easy-checks#281]
Consider referencing the accessibility bookmarklets, they can be used with any web browser and provide a way to look at specific accessibility features like landmarks and headings.
[Accessibility Bookmarklets](https://accessibility-bookmarklets.org/)

**Comment by iadawn** [comment]
Hi @jongund, the bookmarklets created for the resource were created based on a number of existing bookmarklets which are in the acknowledgements. One of the requirements for any bookmarklets that were used was that they not rely on any third party libraries or references. This was to allow for the tool to work regardless of any organisational security that might impose limits on what can be accessed. My understanding is that the Accessibility Bookmarklets host the relevant JavaScript on their own servers so would not be usable in this case.

Additionally, Easy Checks is not intended to link out to other tools as this introduces an additional maintenance burden.

The [Evaluation Tools List](https://www.w3.org/WAI/test-evaluate/tools/list/) would be a more suitable place to link to the Accessibility Bookmarklets.

Kevin
