### ISSUE TITLE
metadata!

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#43]

**Comment by lakeen** [comment]
I can work on creating metadata.  When do you need it? I won't be able to get to it until Thursday or Friday.

**Comment by slhenry** [comment]
Thanks! We hope to publish the updated page on Thursday. I can add the metadata later if needed.

**Comment by vuxcaleb** [comment]
Suggestion:
`<meta name="description" content="This page helps you assess the accessibility of a web page. With these simple steps, you can get an idea if accessibility is addressed in even the most basic way.">`

See Google Preview: https://slerpee.com/edit/z12GwfWuBgrxePaDpQpZWQ

Notice that "if" was swapped for "whether or not" so we could fit the entire sentence in the Google Preview and not change the idea.

Thoughts?

**Comment by slhenry** [comment]
Added: https://github.com/w3c/EasyChecks/commit/84a12f4ea03a5c18e12dfa54da7d84aa30fbcf5c#diff-eacf331f0ffc35d4b482f1d15a887d3b

If anyone has any other, we can add that at any time.

**Comment by lakeen** [comment]
I'm working on more.

**Comment by lakeen** [comment]
Any or all of these can be modified or deleted, specifically date and description:
OG: http://ogp.me/ - you can add image for OG if you want to keep this in.
Dublin Core: http://dublincore.org/

<html lang="en" xmlns:og=http://ogp.me/ns# xmlns:fb="http://www.facebook.com/2008/fbml">
<head>

<link title="schema(DC)" rel="schema.dc" href="http://purl.org/dc/elements/1.1/"/>
<meta name="dc.language" content="eng" />
<meta name="dc.source" content="W3C Web Accessibility Initiative (WAI)" />
<meta property="og:site_name" content="Web Accessibility Initiative"/>
<meta property="og:type" content="article" />
<meta property="og:image" content="" />

<meta name="dc.title" content="Easy Checks A First Review of Web Accessibility | W3C Web accessibility Initiative" /> 

<meta property="og:title" content="Easy Checks A First Review of Web Accessibility | W3C Web accessibility Initiative" />

<meta property="twitter:title" content="Easy Checks A First Review of Web Accessibility | W3C Web accessibility Initiative" />

<meta name='description' content='This page helps you assess the accessibility of a web page. With these simple steps, you can get an idea if accessibility is addressed in even the most basic way.'/>

<meta property="og:description" content="This page helps you assess the accessibility of a web page. With these simple steps, you can get an idea if accessibility is addressed in even the most basic way." />

<meta property="twitter:description" content="This page helps you assess the accessibility of a web page. With these simple steps, you can get an idea if accessibility is addressed in even the most basic way." />

<meta name="dc.contributor" content="W3C Web accessibility" />
<meta name="dc.subject" content="Page Title" />
<meta name="dc.subject" content="Alt Attributes" />
<meta name="dc.subject" content="Headings" />
<meta name="dc.subject" content="Contrast ratio" />
<meta name="dc.subject" content="Resize text" />
<meta name="dc.subject" content="Keyboard Access" />
<meta name="dc.subject" content="Visual Focus" />
<meta name="dc.subject" content="Web Forms" />
<meta name="dc.subject" content="Moving web content" />
<meta name="dc.subject" content="Flashing Web Content" />
<meta name="dc.subject" content="blinking Web Content" />
<meta name="dc.subject" content="Multimedia alternatives" />
<meta name="dc.subject" content="Audio alternatives" />
<meta name="dc.subject" content="HTML structure" />
<meta name="dc.subject" content="Web Accessibility" />
<meta name="dc.subject" content="W3C WAI" />
<meta name="dc.subject" content="Web Accessibility Initiative" />
<meta name="dc.date" content="2016-12-29" /> 
<meta name="dc.identifier" content=" https://www.w3.org/WAI/EasyChecks/" />
<meta rel="canonical" href=" https://www.w3.org/WAI/EasyChecks/" />
<meta name="dc.type" content="Text" />
<meta name="dc.type" content="Web page" />
<meta name="dc.rights" content="Public Domain" />

**Comment by slhenry** [comment]
Added most. Fixed capitalization of Web Accessibility Initiative and added (WAI).

Did not tweak any of the dc.subjects (capitalization is inconsistent - I assume it doesn't matter much if at all)

EOWG: Would someone do a QA pass on this?

**Comment by slhenry** [comment]
@yatil What's the best way to handle <html lang="en" xmlns:og=http://ogp.me/ns# xmlns:fb="http://www.facebook.com/2008/fbml"> with the php includes?

**Comment by yatil** [comment]
@lakeen – I have added markdown markup to show your code block.

@slhenry – I guess we will have this metadata on all pages eventually, so I will add it to the header, and give us a possibility to add that metadata, too.

**Comment by yatil** [comment]
@lakeen Should the `title`, `dc:title`, `twitter:title` really include “Web Accessibility Initiative”?

@slhenry I have implemented a way to use metadata with the php include :-)

**Comment by lakeen** [comment]
@yatil Yes I believe that it is good practice.  I think you want the description to include the organization that is responsible for the content.  It's not a requirement just what we've always done at the library.  description = Page title | Library of Congress

**Comment by yatil** [comment]
@lakeen Thanks!

**Comment by yatil** [comment]
BTW, I used @adactio’s method to condense some of the metadata and not repeat it. https://adactio.com/journal/9881 – it is already live at https://www.w3.org/WAI/eval/preliminary It has not been tested yet. (I’ll do that Monday.)

**Comment by lakeen** [comment]
@yatil sounds good.  Thanks! I don't normally write metadata so I took my best shot.

**Comment by slhenry** [comment]
Thanks @yatil and @lakeen ! ! !

**Comment by yatil** [comment]
@slhenry Please take a look at my comments here – should be minor https://github.com/w3c/EasyChecks/commit/754ffc1e02ff3e09bb21cd090bca55df11fa0819

**Comment by vuxcaleb** [comment]
@lakeen thank you!!!!

**Comment by slhenry** [comment]
a couple validation issues - I didn't look to see if they are legit and ought to be corrected, or OK to ignore...

https://validator.w3.org/nu/?doc=https%3A%2F%2Fcdn.rawgit.com%2Fw3c%2FEasyChecks%2F99e18b699a2c466d5d86feccf6fa9a3a44f916f2%2Findex.html

**Comment by slhenry** [comment]
@yatil -- I had seen your comments in  754ffc1 and didn't think I needed to so anything about them?

**Comment by yatil** [comment]
@slhenry I’m looking into the validation errors. You might want to remove the copyright metadata and use the correct canonical link (that makes the Github version disappearing from Search Engines and pointing to the version on w3.org. I can send in a pull request once I have figured out the validation stuff.

**Comment by slhenry** [comment]
@yatil reminder to figure out validation issues. Not urgent. I'm just addressing issues now. :-)

Thanks!

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
