### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-easy-checks#45]
In general font size seems too small but especially:

<code><a href="http://www.w3.org/WAI/demos/bad/before/home">www.w3.org/WAI/demos/bad/before/home</a></code>

**Comment by yatil** [comment]
Hi Laura, this will be addressed in the redesign, but I question the use of the `<code>` element for the URL here anyway. Do we really need to put the URL here or are we able to just link “inaccessible home page”, @slhenry & @vuxcaleb?

![Screenshot of the small text](https://cloud.githubusercontent.com/assets/58862/21135672/ffa461b0-c122-11e6-88ce-da587dfa74ce.png)

**Comment by slhenry** [comment]
# Font size:
I checked the font size of the overall page and <code> in a few browsers, and they all handle it differently. :( I propose that we take out of the CSS for code "font-size: 95%;"

# URL
I think the decision to include the URL was to support people who print the instructions. (For some people, that is much easier than toggling back and forth, or having multiple windows displayed.) I propose that we leave it as is for this version, and we can address it later if people think it is important.

# code on URLs
I propose that we leave it as is for this version, and we can address it later if people think it is important.

OK?

**Comment by lakeen** [comment]
I don't think that a link should be wrapped in a <code> tag.  If you want to leave it in for this version I'm ok with that but I do think it should be removed and the font size for the link should be fixed in this version if possible.

**Comment by yatil** [comment]
* **Font Size:** +1 to remove font-size: 95% for `<code>`. I guess the difference of the browsers depend a bit on the chosen monospace font and on how the font size is rounded (I think it is 16px ⨉ 0.90 ⨉ 0.95 = 13.68px).
* **URL:** I guess we will have a good print stylesheet that automatically shows the URL after links using CSS once the redesign is upon us :-)
* +1 to postpone a decision on the code element on the URL, it is a secondary (tertiary?) issue imo.

**Comment by bakkenb** [comment]
+1 for changing font size as well. 
Okay with leaving URL and/or addressing it later.

**Comment by slhenry** [comment]
CSS for [code] "font-size: 95%;"  <-- deleted

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
