### ISSUE TITLE
Encourage thorough accessibility evaluation

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-easy-checks#49]
[minor] This title does not really read well to me. Maybe "Explore Further" or such?

Also, I think the "encourage" aspect assumes too much and needs explanation in the text. Maybe something brief like "The following resources can help you or someone else in your team carry out further analysis".

**Comment by slhenry** [comment]
I mildly think it's good as is and not worth the additional words to further explain it. Also, it's more than "you or someone else in your team" -- may people don't have the skills in their team and will need outside help for more evaluation.

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
