### ISSUE TITLE
[Easy Checks] "Alt" alternatives for future version

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-easy-checks#52]
priority: strong suggestion for future versions
location: Image text alternatives ("alt text")
current wording: We only discuss the alt attribute which implies if that's not used, the image fails.
suggested revision: We should include, even if only in a couple of lines, other options for alt text (aria-label, etc.)
rationale: incomplete - possibly inaccurate info - without this.

**Comment by sdeschamps-orange** [comment]
+1

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
