### ISSUE TITLE
[Easy Checks] Learn more about

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-easy-checks#55]
should we add links to appropraite sections of the tutorials under the various 'learn more about' sections?
eg. https://www.w3.org/WAI/tutorials/page-structure/headings/ for Headings

**Comment by yatil** [comment]
Hi Andrew, with the page structure tutorial in flux right now, I think we should postpone that until we have a stable version out.

**Comment by slhenry** [comment]
+1 to both
