### ISSUE TITLE
Expand / Collapse Buttons

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-easy-checks#6]
I see where the expand and collapse buttons have been added to the github version.  Thanks so much.  However, they are wonky because the + and - graphics aren't showing up.  As best I can tell it's not affecting the illustrations, but if that can be fixed it would be one less variable to deal with.

That said, for the sake of giving the illustrations much needed breathing room, I actually preferred the version without the expand and collapse buttons.  Personally I find those buttons more annoying than helpful, but that's a usability issue and this is just my experience.  

However the issue of giving illustrations more space is different.  So I'm strongly in favor of getting rid of the expand / collapse buttons in the next version.  If others think it's important to hide, then there are other ways to do this that do not require an indent (and thus loss of width) for the hidden content when it is displayed.

**Comment by vuxcaleb** [comment]
@slhenry my opinion is this issue should be closed and Easy Checks should adopt the standards from the redesign once they are defined. We should publish as is.

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
