### ISSUE TITLE
maybe pre-launch - suggest using another example for "Keyboard instructions: Ctrl for Windows, cmd for Mac"

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-easy-checks#81]
Some of the keyboard instructions are different for Windows and Mac; for example, "Ctrl" verses "cmd" in:
    For Windows: With the keyboard: Ctrl+Alt+6, then down arrow key to "Heading structure".
    For Mac: With the keyboard: cmd+Alt+6, then down arrow key to "Heading structure".
To reduce clutter, these are listed as:
    With the keyboard: Ctrl/cmd+Alt+6, then down arrow key to "Heading structure".
For such instructions, Windows users press the Ctrl key, and Mac users press the cmd key.

When I select Ctrl+Alt+6, then down arrow key to "Heading structure", using Windows+FF (or IE) my browser flips 180 degrees.

**Comment by yatil** [comment]
> When I select Ctrl+Alt+6, then down arrow key to "Heading structure", using Windows+FF (or IE) my browser flips 180 degrees.

Sorry, I just laughed out loud. 😜 (As a German I am a Schadenfreude expert.) I guess there might be a shortcut collision.

**Comment by slhenry** [comment]
I changed the example at https://www.w3.org/WAI/eval/preliminary#ctrlcmd

However, we do still have that instruction elsewhere on the page **_for IE WAT only_**.

For me in IE with WAT, Ctrl+Alt+6, then down arrow key did what we say. :-)
But it didn't do the browser flip in FF or IE. So maybe it's a later OS or a hardware thing?

@lakeen - Did you have IE WAT loaded when it flipped browser?

If not, could you load it and see if it works to get to WAT or flips the browser?

If so, probably the next step is to figure out what is capturing the keystrokes, and how common it is, and if we want to note it &/or figure out a work-around...

**Comment by HerinHentry** [comment]
Hi All,
I have experienced the same screen rotation with Hot Keys before. If it is happening in FF, its most likely due to the Intel processor Hot Keys.
Please refer to Hotkey Method in https://www.intel.com/content/www/us/en/support/graphics-drivers/000005491.html
The workaround is editing the registry. I do not have the exact details now. Will be able to find out from another colleague.
Ta

**Comment by yatil** [comment]
@lakeen It looks like you held ctrl+alt while pressing the down arrow key. You should release ctrl and alt before pressing down. (I think that was pretty apparent from the description, but maybe we need to be clearer.)

@HerinHentry I strongly feel that “editing the registry” is not a work around and that no ordinary human should do it (and we should not include it in our documents). :-)

**Comment by lakeen** [comment]
@yatil You are correct. I was holding down ctl+alt+4 then selecting down arrow  which is how I read the instruction.  I strongly feel that this instruction should be clearer.

cntl+alt+4 to me indicates that all 3 keys should be held down.

@slhenry  I do not have IE WAT loaded.  I was initially testing the general keyboard instruction for Windows and Mac

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
