### ISSUE TITLE
Title of resource

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#84]
Current title is ["Easy Checks - A First Review of Web Accessibility"](https://www.w3.org/WAI/eval/preliminary)

Please skim the document, and read:
* [Analysis of audience, criteria for checks](https://www.w3.org/WAI/EO/wiki/Eval_Analysis#Preliminary_Evaluation_Analysis)
* [Tasks & Use Cases](https://www.w3.org/WAI/EO/wiki/Eval_Analysis#Tasks_.26_Use_Cases) for this and other eval resources

Please carefully think about these considerations:
* It is **_vital_** that the tile (or at least subtitle) convey that this is not a comprehensive or definitive evaluation.
* We have high SEO on "Easy Checks" &mdash; our resource is the first listing (after ads) in search engines I checked, and the first 3 listings in a popular one.
* Lots of [tweets with "Easy Checks"](https://twitter.com/search?q=%22Easy%20Checks%22%20a11y&src=typd) and not the rest of the title
* Lots of references to "Easy Checks", such as [Harvard Library (pdf)](http://urc.library.harvard.edu/files/harvardlibraryux/files/accessibilitytraining_easychecks.pdf), [SitePoint](https://www.sitepoint.com/easy-checks-website-accessibility/), [Nomensa info graphic](https://www.nomensa.com/blog/2017/making-your-site-accessible-infographic), [AccessIQ]( http://www.accessiq.org/news/w3c-column/2013/07/easy-checks-a-path-to-wcag-simplicity), [Interactive Accessibiility]( http://www.interactiveaccessibility.com/news/wcag-20-easy-accessibility-checks#.WZcVH1Xfrb0),  [presentation (ppt)](https://groups.drupal.org/files/Accessibility%20Easy%20Checks.ppt), and many more…

Please at least skim these previous title ideas and discussions:
* https://www.w3.org/WAI/EO/wiki/Eval_Analysis#Title_ideas
* https://www.w3.org/2013/01/11-eo-minutes#item03

Note: We'll probably change the URI in the redesign WAI website.

What do you think of leaving the title as is, or considering changing the title? Other considerations in addition to above?

If change, please provide specific suggestions with rationale, pros, cons, and such.

**Comment by slhenry** [comment]
A few specific thoughts:
* These checks aren't all _easy_ for some people -- especially the Forms checks.
* A task that was included in the redesign analysis was something like "What are common accessibility problems in websites?"

A brainstorm I had was:
> First Checks for Some Common Accessibility  [Errors|Bugs|Problems|Barriers]  _(and leave "Some" out of short names, e.g., nav)_
* CON: loses well known "Easy Checks"
* not sure that "First Checks" is good intro phrase, although it does pick up some from the current title (Easy Checks: A First ...)

I am **_very_** hesitant to give up the recognition of "Easy Checks". So another idea would be:
> Easy Checks for Some Common Web Accessibility [Errors|Bugs|Problems|Barriers]  _(and leave "Some" out of short names, e.g., nav)_
* PRO: keeps well known "Easy Checks"
* CON: Not all checks are "easy" for all of target audience.

For both above:
* PRO: I think "common problems" is something people will look for in SEO and nav surfing.
* Question: Does "Some Common" adequately convey not comprehensive or definitive?

**Comment by yatil** [comment]
My frank opinion is: Keep EasyChecks for now. In the next iteration, break the checks up on individual pages, tag them individually with easy, medium, technical or something like that and provide a form/configurator where people can select what type of tips they want to have displayed.

Reasoning: We have to provide more guidance for checks of all sorts, just providing things that are easy to do will not be enough in the long run, and most accessibility tests are also not easy and we should reflect that.

We, of course, should have a page titled “easy checks” that has links to all easy checks.

**Comment by dboudreau** [comment]
I think Star Wars and the Montreal Canadians are two franchises that have a pretty bad name. But it's too late to change either of them now. I feel the same way about Easy checks, especially based on what you shared, @slhenry. I think we're overthinking how people might feel about us saying these checks are easy. I don't see a lot of value in changing the title now - if it radically made the resource better, then yes, but changes like the ones we've discussed so far seem to me like trading 4 quarters for a dollar...

**Comment by nrhsinclair** [comment]
+1 to Robert's point regarding what are users looking for. 
suggest, First Checks: How to Get Started with Web Accessibility or First Checks: How to Identify Common Accessibility Problems

**Comment by bakkenb** [comment]
Please read [renaming discussion from 01 September 2017 Meeting](https://www.w3.org/2017/09/01-eo-minutes.html#item04) prior to adding more to this thread.

**Comment by vmmiller** [comment]
I'd leave the words "Easy Checks" in the title as it seems to be branded as such.

**Comment by dboudreau** [comment]
I still feel the same way about the title of this resource. I'd hate to lose whatever traction we've created with Easy checks. I'm sort of feeling like we're overthinking this one.

**Comment by iamjolly** [comment]
I'm OK with leaving the name as-is or renaming it to Basic Accessibility Checks (credit to Roy for that suggestion on 1 Sept 2017 call). Either option works well enough (for now), and we can always rename later if we decide it isn't findable or descriptive enough for the content within. I do want us to consider the thinking that @James-Green brought up about findability [during this portion of the discussion](https://www.w3.org/2017/09/01-eo-minutes.html#item04) and not feel beholden to "Easy Checks" because of SEO. We can always keep that phrase in the content if it's important for search reasons. Proper use of redirects will handle the rest.

**Comment by nitedog** [comment]
I don't feel too strongly but I have heard critique along the lines of "easy checks isn't really all that easy", including from some opinion leaders. I would prefer something like "initial", "basic", or "cursory" checks.

**Comment by slhenry** [comment]
Eric says in [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-1-Sep-2017/results#xq2):

> I think we need to be practical with this and move on. If there is no clear advantage of renaming a resource in a certain way, we should leave as is and put our energy to work on the content of documents.

**Comment by slhenry** [comment]
Seems pretty split among votes for keeping "Easy Checks" and votes for changing that. :-/

I'm even split myself -- my two shoulders have been arguing about it for weeks.

I wonder if this is a good thing to ask WAI IG's input on? If so, I think it would be good to include an alternative for consideration.

- I kinda like "Basic Checks"; however, if we're getting rid of the known "Easy Checks", do we want to at least keep the word "First" so there's that association with the old name?<br/>Also, **"First Checks" seems like a better call to action** - it's almost **imperative "First, check for ..."**
- I still think it would be good to include "Common"... I think people look for "common" or "top 10" or such -- and in previous testing of navigation, they didn't find answer to that question.
- ... and then either Errors or Bugs or Problems or Barriers or Issues. I think in last telecon, Laura suggested "Issues". Personally, I like that best.

So right now if we don't use "Easy Checks", I'm leaning towards:

**First Checks for Common Web Accessibility Issues**

and would also be OK with:
Basic Checks for Common Accessibility Issues

**Comment by bakkenb** [comment]
I like "First Checks for Common Web Accessibility Issues" over "Basic Checks..."

Rationale: I know we (and our audience) is going to immediately start using a nickname for this resource, like we/they did in the past and have done for other resources. The nickname "FirstChecks" is better than "BasicChecks" because first checks are generally basic, but it more importantly it also implies that there is more to be done after these first ones are complete. "BasicChecks" as a nickname could imply, "do this and you are good to go".

I vote for **First Checks for Common Web Accessibility Issues**

**Comment by nrhsinclair** [comment]
+1 First Checks for Common Web Accessibility Issues

**Comment by iamjolly** [comment]
Sold!
+1 for **First Checks for Common Web Accessibility Issues**

**Comment by yatil** [comment]
-1 to asking WAI IG.

I don’t see clear advantages for changing the name. I see a lot of disadvantages at the moment.

Strong +1 to **keeping EasyChecks** and move on.

**Comment by vmmiller** [comment]
@yatil to +1 to keeping Easy Checks and move on and later, when content changes, review the position.

**Comment by slhenry** [comment]
We plan to do usability improvements in a [next generation](https://www.w3.org/WAI/EO/wiki/Easy_Checks_Next_Gen) of this resource. Improving the usability will make the whole document seem easier, but will not make the checks themselves much easier. Some people really do not find these checks easy to do, especially the Forms checks. Sharron & I have seen this first hand from hands-on training on it.

**We do **_not_** have plans to expand it to include more checks**.<br/> (Not saying we never will, but that it is not in the charter for 2017-2020.)

**Comment by sharronrush** [comment]
Resolved to leave name as is until content changes after launch

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
