### ISSUE TITLE
Width of figure box

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#88]
Some are too wide, like:
<img width="696" alt="wide box" src="https://user-images.githubusercontent.com/6991814/34009919-62cbe632-e0d0-11e7-9621-6877b1ec7d0f.png">

some not, like:
<img width="683" alt="notwide" src="https://user-images.githubusercontent.com/6991814/34009915-5eb3a80a-e0d0-11e7-9c24-afc51cb23709.png">

**Comment by yatil** [comment]
The redesign has different boxes and other ways to align them. The old way was never a good implementation with many floating and alignment bugs.

https://w3c.github.io/wai-website/test-evaluate/easychecks/ Uses no boxes at all, but I will update to the standard boxes as soon as the content is ready to be ported to the new design, see #87. Those boxes will always have full width. When we have two or three boxes next to each other we can split the full width into three columns. We might be able to use [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) for these figures, but I’d prefer simple solutions and no exceptions to general design components.

**Comment by yatil** [comment]
Or maybe we could use flexbox. I might look into it.

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
