### ISSUE TITLE
checks instruction update/correction

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#89]
From https://lists.w3.org/Archives/Public/wai-eo-editors/2018Mar/0006.html :

Under bad checks for images, instructions are provided to check basic structure with WebDev toolbar.

Number two states to select "Disable Images", then "Disable All Images".

In Chrome, I have the option to Disable Images, but not Disable All Images.
In Firefox, I have the option to Hide Images.

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
