### ISSUE TITLE
Filter for toolbar and more (for later version)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#9]
Currently there is one page that includes instructions for both a Firefox toolbar and an IE toolbar.

Idea: User can pick one and get only the instructions for that one.

Other ideas for filters:
- mouse or keyboard instructions (this would simplify the info a fair bit since now there are both)
- Mac or PC

**Comment by slhenry** [comment]
oops duplicated idea in https://github.com/w3c/EasyChecks/issues/17
"Users can Expand All instructions for one tool and not the other."
closing that issue...

**Comment by iadawn** [comment]
Closed as no longer relevant to new version of the resource
