### ISSUE TITLE
2.1 SC-related potential additions

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#96]
At F2F, small group of Andrew, Robert, Sarah, Eric, and Shawn evaluated [new 2.1 SCs](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/) based on this [Criteria for checks](https://www.w3.org/WAI/EO/wiki/Eval_Analysis#Criteria_for_checks).

Analysis and initial recommendations are in this **[google doc](https://docs.google.com/document/d/1BECG9VoXibu_mubn0XbZhOfUg4fcweGxd9JbrxeqOjE/edit#heading=h.jf28f994hxga)**.

Initial recommendation is to add checks related to:
* Orientation
* Reflow
* Non-text contrast
* Text spacing
* Animation from interaction
* Target size

_Note:_ Some could be additions to existing checks and some new checks.

**Comment by iadawn** [comment]
Incorporated into current work updating the resource. The exploration work on possible checks to include is available at: [Possible Easy Checks](https://docs.google.com/document/d/1yXj-s3a_yqYVTCVzVOyOiwmOQN0xc1d9bF77j9khyQQ/edit#heading=h.o9lnmgme04ao)
